version: '3.3'
services:
  web:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: suitecrm-instance
    container_name: suitecrm-obj
    ports: 
      - 80:80
  db:
    image: mysql
    container_name: mysql-suitecrm
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: suitecrm
      MYSQL_USER: suitecrm-user
      MYSQL_PASSWORD: root@scm
    ports: 
      - 3306:3306
    volumes: 
      - mysql-data:/var/lib/mysql
volumes: 
  mysql-data: